### ISSUE TITLE
Transfer ownership to ahkscript community

### ISSUE THREAD

**Issue by aviaryan** [ahkscript/AutoHotkey#15]
If this package is a part of the @ahkscript community, then pull requests will be merged more quickly and issues will be resolved much faster. 
What do you think ?

**Comment by robertcollier4** [comment]
I agree.
https://help.github.com/articles/transferring-a-repository/

**Comment by aviaryan** [comment]
I too am not the admin. If you want I can fork your repo **as ahkscript** and then we will continue the work from there.

**Comment by robertcollier4** [comment]
Repo transferred to @ahkscript organization.
